### ISSUE TITLE
missing translation labels

### ISSUE THREAD

**Issue by Damecek** [caderek/polytopia-languages#17]
In the multiplayer when picking a tribe, in the summary in top is tribepicker.maptype insted of proper label
![269400453_613060089942347_2648202259464890651_n](https://user-images.githubusercontent.com/46635736/146951034-f1a46022-3138-4c5e-a1c1-a7994b75c595.jpg)

**Comment by Damecek** [comment]
same for building.names.harvestfruit
![268805057_5062682993751566_4200290349078880689_n](https://user-images.githubusercontent.com/46635736/146953238-bc05c486-b44c-4e7d-b614-e2445e003ba8.jpg)

**Comment by caderek** [comment]
Yes, there are still a lot of missing keys in the original translation file - I could add them by hand,  like I was doing before, but that's a lot of work (because you have to switch between languages in game to get both the key and original translation). I asked for an updated original English file on the official subreddit: https://www.reddit.com/r/Polytopia/comments/rkqdpj/custom_translations/

Let's see if we get an answer.

**Comment by Damecek** [comment]
typo in unit.names.swordsman, should be unit.names.swordman

**Comment by Damecek** [comment]
@Damecek  cool, let's see what they can provide

**Comment by Damecek** [comment]
Hey @caderek do we have any update on this?

**Comment by watous** [comment]
Hm, a Czech translation. I have made [one](https://github.com/watous/polytopia) but never added here. If you are doing antoher one (well, I translated kind of freely) or anyway, [here](https://github.com/caderek/polytopia-languages/files/8081542/new_keys.txt) I post the missing keys I have found (pre-Diplomacy). I don't know the original strings, though, because I translated right away, sorry.

**Comment by caderek** [comment]
I finally got an updated original, and added missing keys to all existing files. make sure that you read README, as there were some changes to the project's structure. TL;DR - edit [templates](https://github.com/caderek/polytopia-languages/tree/master/templates) not translations folder (translations are now autogenerated from templates).
